"""Reproduce the Track B diagnostic tables offline; never compute a risk verdict.

Run from any directory: python <path>/analyze.py [--check]
The existing CSV is an output under investigation, not accepted market evidence.
"""

import argparse
import csv
import hashlib
from decimal import Decimal, ROUND_HALF_EVEN, localcontext
from pathlib import Path

HERE = Path(__file__).resolve().parent
EVIDENCE = HERE.parent
CSV = EVIDENCE / "USTRY.GCRYUGD5-USDC.GA5ZSEJY-bookseries-2026-02-01_2026-03-01-cap400.csv"
TRADES = EVIDENCE / "USTRY.GCRYUGD5-USDC.GA5ZSEJY-trades-2026-02-01_2026-03-01.csv"
ISSUER = "GCRYUGD5NVARGXT56XEZI5CIFCQETYHAPQQTHO2O3IQZTHDH4LATMYWC"
USDC = "GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN"


def rows(path):
    with path.open(newline="", encoding="utf-8") as stream:
        return list(csv.DictReader(stream))


def number(value):
    if value == "":
        return "null"
    with localcontext() as context:
        context.prec = 100
        return format(Decimal(value).quantize(Decimal("0.0000001"), rounding=ROUND_HALF_EVEN), "f")


def quality(row):
    crossed = (row["best_bid"] and row["best_ask"]
               and Decimal(row["best_bid"]) >= Decimal(row["best_ask"]))
    if crossed:
        return "CROSSED; incomplete"
    if int(row["target_ledger"]) > 61143619:
        return "phantom ask implicated; incomplete"
    return "incomplete; outside known phantom interval"


def table(header, data):
    return ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)] + [
        "| " + " | ".join(str(value) for value in row) + " |" for row in data
    ]


def report():
    samples, trades = rows(CSV), rows(TRADES)
    daily = [row for row in samples if row["day"]]
    if len(samples) != 30 or len(daily) != 28:
        raise ValueError("The pinned input is no longer the 30-point February cap400 run")
    lines = [
        "# February cap400 output: diagnostic appendix",
        "",
        "Generated by `analyze.py`. These are **observed program outputs, not accepted historical risk measurements**.",
        "Every row is incomplete. From 9 February onward the earlier investigation implicates the phantom ask.",
        "An uncrossed row is not certified. No first-warning date is established by this table.",
        "",
        f"Pair: USTRY `{ISSUER}` / USDC `{USDC}`.",
        f"Input: `{CSV.name}`; SHA-256 `{hashlib.sha256(CSV.read_bytes()).hexdigest()}`.",
        "Methodology labels are copied from the CSV, not updated to the current code version.",
        "All monetary columns are USDC except P0 (USDC/USTRY). Display rounds to seven decimal places, half-even.",
        "Exact values remain in the linked CSV. Null is not zero. A displayed zero can be a rounded positive value.",
        "",
        "## Daily samples",
        "",
    ]
    def sample_row(row):
        return [row["day"] or "control", row["target_ledger"], row["sampled_at_utc"],
                number(row["p0"]), number(row["depth_buy_0.02"]), number(row["depth_sell_0.02"]),
                number(row["mc_cost_0.5"]), row["mc_reachable_0.5"],
                row["band"] + "/" + row["band_confidence"], quality(row)]
    header = ["Day", "Ledger", "Sample UTC", "P0", "Buy depth 2%", "Sell depth 2%", "MC 50%", "Reachable", "Observed band/confidence", "Validity"]
    lines += table(header, [sample_row(row) for row in daily])
    lines += ["", "## Additional control samples", ""]
    lines += table(header, [sample_row(row) for row in samples if not row["day"]])
    lines += ["", "## First observed labels in this rejected input", "",
              "These are table lookups, not validated threshold crossings or warning lead times.", ""]
    labels = {}
    for row in daily:
        for flag in sorted(row["flags"].split()):
            labels.setdefault(flag, row)
        if row["band"] == "CRITICAL":
            labels.setdefault("band=CRITICAL", row)
    if labels:
        lines += table(["Label", "First daily row", "Ledger", "Validity"], [
            [flag, row["day"], row["target_ledger"], quality(row)] for flag, row in sorted(labels.items())
        ])
    if not labels:
        lines += ["", "No daily row in cap400 carries a triggered flag or a CRITICAL band. All 28 daily rows say LOW/partial.",
                  "This differs from the earlier shallow run described in the task brief. It does not establish that the asset was safe."]
    controls = [row for row in samples if not row["day"]]
    lines += ["", "Control-row labels (outside the daily sampling grid):", ""]
    lines += table(["Ledger", "Band/confidence", "Triggered flags", "Validity"], [
        [row["target_ledger"], row["band"] + "/" + row["band_confidence"], row["flags"] or "none", quality(row)] for row in controls
    ])
    lines += ["", "Unevaluated flags are preserved separately, not counted as clear or triggered:", ""]
    for flag in sorted({flag for row in daily for flag in row["unevaluated_flags"].split()}):
        lines.append(f"- `{flag}`")
    lines += ["", "## Raw trade checks", ""]
    for offer in ("1822775941", "1824767559"):
        hits = [row for row in trades if offer in (row["base_offer_id"], row["counter_offer_id"])]
        lines.append(f"- Offer `{offer}`: {len(hits)} CSV fills, first ledger `{hits[0]['ledger_seq']}`, last ledger `{hits[-1]['ledger_seq']}`.")
    manipulation = [row for row in trades if row["ledger_seq"] == "61340263"]
    lines += ["", *table(["Ledger", "Offer", "USTRY filled", "USDC paid", "Price n/d"], [
        [row["ledger_seq"], row["base_offer_id"], row["base_amount"], row["counter_amount"], row["price_n"] + "/" + row["price_d"]]
        for row in manipulation]), ""]
    return "\n".join(lines)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = HERE / "daily-output-review.md"
    expected = report()
    if args.check:
        if target.read_text(encoding="utf-8") != expected:
            raise SystemExit("FAIL: diagnostic appendix differs from its pinned CSV")
        print("PASS: diagnostic appendix exactly reproduces the pinned CSV")
    else:
        target.write_text(expected, encoding="utf-8", newline="\n")
        print(target)
